((circleci-transient nil)
 (magit-branch nil)
 (magit-commit nil)
 (magit-fetch nil)
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-pull nil)
 (magit-push nil)
 (magit-run nil)
 (magit-stash nil)
 (magit-tag nil))
